name: studybuddy
description: Flash cards for memorization.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  charts_flutter: ^0.9.0
  intl: ^0.16.1
  path_provider: ^1.6.14
  provider: ^4.3.2+2
  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.10
  sqflite: ^1.3.0
  animations: ^1.1.2
  flutter_launcher_icons: ^0.8.0
  image: ^2.1.19

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logo.png"
  adaptive_icon_foreground: "assets/logo.png"
  adaptive_icon_background: "#9EA7AA"

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Langar
      fonts:
        - asset: fonts/Langar-Regular.ttf